name: azure-blob-copy-action
description: Github action to allow copying to and from Azure Blob Storage
branding:
  icon: "copy"
  color: "red"
inputs:
  action:
    description: Either upload or download
    required: true
    default: upload
  connection_string:
    description: Azure Blob Storage connection string
    required: true
  container_name:
    description: Azure Blob Storage container name
    required: true
  blob_directory:
    description: Directory in Azure to copy from or to
    required: false
  local_directory:
    description: Local directory to copy from or to; this can either be an absolute path or a relative path
    required: true

runs:
  using: node12
  main: dist/index.js
