name: Build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm ci
        run: npm ci

      - name: npm run build
        run: npm run build

      - name: npm run test
        run: npm run test
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
