name: Build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

  workflow_dispatch:
    inputs:
      version:
        description: "If version is specified, does an official build which will create a new commit and a tag."
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm ci
        run: npm ci

      - name: npm run build
        run: npm run build

      - name: npm run test
        run: npm run test
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}

      - name: upload integration test
        uses: ./
        with:
          action: upload
          connection_string: ${{ secrets.CONNECTION_STRING }}
          container_name: tests
          local_directory: .github

      - name: release
        if: github.event.inputs.version
        run: |
          echo "Releasing official build with version ${{ github.event.inputs.version }}..."
          git config user.email "github@ulaval.ca"
          git config user.name "Github actions"
          git add .
          git commit -m "${{ github.event.inputs.version }}"
          git tag -f -m "${{ github.event.inputs.version }}" ${{ github.event.inputs.version }}
          git push --follow-tags
